# Generated by Django 5.1.12 on 2026-03-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_project_annotator_evaluation_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="triton_api_key",
            field=models.CharField(
                blank=True,
                help_text="API key for Triton model deployment",
                max_length=128,
                null=True,
                verbose_name="triton_api_key",
            ),
        ),
    ]
